// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using team_gung_ho_coders_backend.Migrations;

#nullable disable

namespace teamgunghocodersbackend.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("team_gung_ho_coders_backend.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            MovieTitle = "Die Hard"
                        },
                        new
                        {
                            MovieId = 2,
                            MovieTitle = "The Proposal"
                        });
                });

            modelBuilder.Entity("team_gung_ho_coders_backend.Models.MovieReview", b =>
                {
                    b.Property<int>("MovieReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextBody")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("MovieReviewId");

                    b.ToTable("MovieReview");

                    b.HasData(
                        new
                        {
                            MovieReviewId = 1,
                            MovieRating = 5,
                            TextBody = "I loved this movie so very much! It was really, really amazing!"
                        },
                        new
                        {
                            MovieReviewId = 2,
                            MovieRating = 1,
                            TextBody = "This movie was not very good. Total snooze fest."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
